### PR TITLE
Preware 2 App: Change references from ipkg to opkg

### PR DESCRIPTION
**Pull request by KyleMaas**
* Change references from ipkg to opkg.

Open-WebOS-DCO-1.0-Signed-Off-By: Kyle Maas <kylemaasdev@gmail.com>

### CODE REVIEW

**Comment by Herrie82** [comment]
The prerm and postinst would need to be updated as well: https://github.com/webOS-ports/preware/blob/master/control/prerm and https://github.com/webOS-ports/preware/blob/master/control/postinst.

Also preware.org is gone, so all references in the app should point to the new domain which is preware.net

**Comment by KyleMaas** [comment]
How does that look?

**Comment by Herrie82** [comment]
Seems I might have been wrong altogether. Seems we're no longer the version in src but the one in oe-service. The prerm and postint seems to be takes care by the recipe as well?

https://github.com/webOS-ports/meta-webos-ports/blob/fido/meta-luneos/recipes-luneos/services/org.webosinternals.ipkgservice.bb#l19

**Comment by KyleMaas** [comment]
I think that's correct for the default feeds - those weren't really specified in the Preware 2 app.  The corrections I made there were for a sample file.  However, I still think it's good to make those changes for consistency's sake.

Our next step on this IMHO would be to try building and testing it.  Seeing as I don't currently have a good build environment for this available, can you give it a try please?

**Comment by Herrie82** [comment]
It doesn't hurt indeed. I doubt they'll be used in a build though (and maybe shouldn't even be in the repo anymore (the src folder that is). I'll merge it as is.

**Pull request merged**
